// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    'getting-started',
    'guide',
  ],
  astsSidebar: [{type: 'autogenerated', dirName: 'asts'}],
  spectraSidebar: [{type: 'autogenerated', dirName: 'spectra'}],
  webapiSidebar: [{type: 'autogenerated', dirName: 'webapi'}],
};

export default sidebars;
